//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appGestionTickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int IdTicket { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public string Solucion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Responsable Responsable { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
